Repository be-Cycled/beCycled-frontend, pull requests merged in 2021-07, with the labels that each got.

#55 Исправлены HTTP-методы для присоединения/покидания сообщества
  src/app/global/domain/services/community/community.service.ts
Labels: bug

#65 Issue 63
  src/app/global/cdk/components/event-filter/components/event-filter/event-filter.component.ts
Labels: bug

#72 Не работал календарь на мобилке
  src/app/global/cdk/components/header/components/header/header.component.html
  src/app/modules/add-event/components/add-event/add-event.component.html
  src/app/modules/add-event/components/add-event/add-event.component.scss
  src/app/modules/add-event/components/add-event/add-event.component.ts
  src/app/modules/auth/components/registration/registration.component.html
Labels: bug

#75 Хотфиксы после переезда на новое API событий
  src/app/global/cdk/components/abstract-event-list-page.ts
  src/app/global/cdk/components/event-card/abstract-event-card.ts
  src/app/global/cdk/components/event-card/competition/competition.component.html
  src/app/global/cdk/components/event-card/workout/workout.component.html
  src/app/global/cdk/components/event-filter/components/event-filter/event-filter.component.ts
  src/app/global/domain/domain.module.ts
  src/app/global/domain/models/event/base-event.ts
  src/app/global/domain/services/affiche/affiche.service.ts
  src/app/global/domain/services/competition/competition.service.ts
  src/app/global/domain/services/event/event.service.ts
  src/app/global/domain/services/feed/feed.service.ts
  src/app/global/domain/services/workout/workout.service.ts
  src/app/global/dto/event/base-competition-dto.ts
  src/app/global/dto/event/base-event-dto.ts
  src/app/global/dto/event/base-workout-dto.ts
  src/app/global/dto/route/route-dto.ts
  src/app/global/models/events.ts
  src/app/global/models/index.ts
  src/app/global/utils/event/event.ts
  src/app/modules/add-event/add-event.module.ts
  src/app/modules/add-event/components/add-event/add-event.component.html
  src/app/modules/add-event/components/add-event/add-event.component.ts
  src/app/modules/affiche/affiche.module.ts
  src/app/modules/affiche/containers/affiche-container/affiche-container.component.ts
  src/app/modules/communities/containers/single-community-container/single-community-container.component.html
  src/app/modules/communities/containers/single-community-container/single-community-container.component.ts
  src/app/modules/competition-page/components/competition-page/competition-page.component.html
  src/app/modules/competition-page/components/competition-page/competition-page.component.scss
  src/app/modules/feed/containers/feed-container/feed-container.component.ts
  src/app/modules/feed/feed.module.ts
  src/app/modules/profile/containers/profile-container/profile-container.component.html
  src/app/modules/profile/containers/profile-container/profile-container.component.ts
  src/app/modules/workout-page/components/workout-page.component.html
  src/app/modules/workout-page/components/workout-page.component.scss
  tslint.json
Labels: critical

#86 Фильтр перестал работать в афишах и ленте
  src/app/global/cdk/components/event-card/event-info/event-info.component.html
  src/app/global/cdk/components/event-card/event-info/event-info.component.ts
  src/app/global/cdk/components/event-filter/components/event-filter/event-filter.component.ts
  src/app/global/cdk/components/header/components/header/header.component.ts
  src/app/global/domain/models/user/user.ts
  src/app/modules/profile/containers/profile-container/profile-container.component.html
Labels: bug

#105 feat: Удаление организации
  src/app/global/domain/services/community/community.service.ts
  src/app/modules/communities/communities.module.ts
  src/app/modules/communities/components/single/community-single-settings/community-single-settings.component.html
  src/app/modules/communities/components/single/community-single-settings/community-single-settings.component.scss
  src/app/modules/communities/components/single/community-single-settings/community-single-settings.component.ts
  src/app/modules/communities/services/community-store/community-store.service.ts
  src/styles.scss
Labels: enhancement

#106 feat: Обновление пароля у пользователя
  src/app/global/domain/services/community/community.service.ts
  src/app/global/domain/services/user/user.service.ts
  src/app/modules/profile/containers/profile-container/profile-container.component.html
  src/app/modules/profile/containers/profile-container/profile-container.component.scss
  src/app/modules/profile/containers/profile-container/profile-container.component.ts
  src/app/modules/profile/profile.module.ts
Labels: enhancement

#107 fix: Исправлены фавиконки
  src/assets/favicons/android-chrome-192x192.png
  src/assets/favicons/android-chrome-384x384.png
  src/assets/favicons/apple-touch-icon.png
  src/assets/favicons/browserconfig.xml
  src/assets/favicons/favicon-16x16.png
  src/assets/favicons/favicon-32x32.png
  src/assets/favicons/favicon.ico
  src/assets/favicons/mstile-150x150.png
  src/assets/favicons/safari-pinned-tab.svg
  src/assets/favicons/site.webmanifest
  src/assets/icons/icon-128.png
  src/assets/icons/icon-144.png
  src/assets/icons/icon-152.png
  src/assets/icons/icon-16.png
  src/assets/icons/icon-192.png
  src/assets/icons/icon-32.png
  src/assets/icons/icon-36.png
  src/assets/icons/icon-384.png
  src/assets/icons/icon-48.png
  src/assets/icons/icon-512.png
  src/assets/icons/icon-72.png
  src/assets/icons/icon-96.png
  src/index.html
Labels: enhancement

#109 feat: Тулбар для PWA
  src/app/app.component.html
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/global/cdk/components/index.ts
  src/app/global/cdk/components/toolbar/components/toolbar/toolbar.component.html
  src/app/global/cdk/components/toolbar/components/toolbar/toolbar.component.scss
  src/app/global/cdk/components/toolbar/components/toolbar/toolbar.component.spec.ts
  src/app/global/cdk/components/toolbar/components/toolbar/toolbar.component.ts
  src/app/global/cdk/components/toolbar/services/toolbar/toolbar.service.spec.ts
  src/app/global/cdk/components/toolbar/services/toolbar/toolbar.service.ts
  src/app/global/cdk/components/toolbar/toolbar.module.ts
  src/app/global/cdk/index.ts
  src/app/modules/auth/containers/auth-container/auth-container.component.ts
  src/styles.scss
Labels: enhancement

#113 fix: Исправлено название свойства при загрузке картинок
  src/app/modules/add-event/components/add-event/add-event.component.ts
  src/app/modules/communities/components/single/community-single-settings/community-single-settings.component.ts
  src/app/modules/profile/containers/profile-container/profile-container.component.ts
Labels: enhancement

#114 feat: Страница "О проекте"
  src/app/app-routing.module.ts
  src/app/global/cdk/components/header/components/header/header.component.html
  src/app/global/cdk/components/menu/components/menu/menu.component.html
  src/app/modules/about/about-routing.module.ts
  src/app/modules/about/about.module.ts
  src/app/modules/about/containers/about-container/about-container.component.html
  src/app/modules/about/containers/about-container/about-container.component.scss
  src/app/modules/about/containers/about-container/about-container.component.ts
  src/assets/.gitkeep
  src/assets/logo.svg
  src/assets/logos/instagram.png
  src/assets/logos/sport-arteria-logo.png
  src/assets/logos/telegram.svg
  src/assets/logos/vk.svg
  src/assets/logos/waliot.svg
Labels: enhancement
